### ISSUE TITLE
Question Regarding `onExit` callback.

### ISSUE THREAD

**Issue by Imgkl** [jorgefspereira/plaid_flutter#119]
<img width="1327" alt="image" src="https://github.com/jorgefspereira/plaid_flutter/assets/25414681/d9c9c5ca-89c5-4963-891b-1cb013f9d3b2">

On `onExit`'s LinkEvent callback, We noticed that we are getting status as `institution_not_found`, package's API documentation say that

> User exited the Link flow after unsuccessfully (no results returned) searching for a financial institution

But we are also getting institution name as well. In my case, it says Charles Schwab. There are many entries for "Institution Not found" for banks that 100% are valid and functional, like Etrade, Chase, Schwab etc. Need to understand what is going on here.

**Comment by jorgefspereira** [comment]
Hi @Imgkl, upon testing I'm getting the same results if the user **selects** the institution -> goes **back** -> exits the flow.

It seems to me if the users select the institution it will always return the institution name and id...even if it goes back to the first screen and exit.

Hope it helps. I'm closing the issue since I'm not able to change this behavior on this integration plugin.
